require('render-markdown').setup({
    render_modes = {'n', 'v', 'i', 'c'},
    heading = {
        enabled = true,
        sign = false,
        position = 'inline',
        icons = {'#', '#', '#', '#', '#', '#'},
        width = {'full', 'block', 'block', 'block', 'block', 'block'},
        min_width = 60,
        border = true,
        above = '▄',
        below = '▀',
        backgrounds = {
            'RenderMarkdownH1Bg',
            'RenderMarkdownH2Bg',
            'RenderMarkdownH3Bg',
            'RenderMarkdownH4Bg',
            'RenderMarkdownH5Bg',
            'RenderMarkdownH6Bg',
        },
        foregrounds = {
            'RenderMarkdownH1',
            'RenderMarkdownH2',
            'RenderMarkdownH3',
            'RenderMarkdownH4',
            'RenderMarkdownH5',
            'RenderMarkdownH6',
        },
    },
    code = {
        enabled = true,
        sign = false,
        style = 'full',
        position = '',
    },
    dash = {
        enabled = true,
        icon = '─',
        width = 'full',
        highlight = 'RenderMarkdownDash',
    },
    quote = {
        enabled = true,
        icon = '▋',
        highlight = 'RenderMarkdownQuote',
    },
    bullet = {enabled = false},
    checkbox = {enabled = false},
    pipe_table = {enabled = false},
    link = {enabled = false},
    sign = {enabled = false},
})
