source ~/dotfiles/shell/rc.sh

source ~/.zsh/settings.zsh
source ~/.zsh/lib.zsh
source ~/.zsh/colors.zsh
source ~/.zsh/bindings.zsh
source ~/.zsh/prompt.zsh
source ~/.zsh/plugins.zsh
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
